services:
  - type: web
    name: janata-audit-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
